# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from User import User

user_controller = User()

from PyQt5 import QtCore, QtGui, QtWidgets
import dashboard_admin as da
import insert_user as iu
import update_user as uu
import login
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 801)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 781))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;   /* biru muda lembut */\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game-console (1).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 160, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_insertUser = QtWidgets.QPushButton(self.frame)
        self.pushButton_insertUser.setGeometry(QtCore.QRect(30, 350, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_insertUser.setFont(font)
        self.pushButton_insertUser.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game_14776131.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_insertUser.setIcon(icon)
        self.pushButton_insertUser.setObjectName("pushButton_insertUser")
        self.pushButton_dashboardA = QtWidgets.QPushButton(self.frame)
        self.pushButton_dashboardA.setGeometry(QtCore.QRect(30, 260, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dashboardA.setFont(font)
        self.pushButton_dashboardA.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/xbox_906325.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dashboardA.setIcon(icon1)
        self.pushButton_dashboardA.setObjectName("pushButton_dashboardA")
        self.pushButton_updateUser = QtWidgets.QPushButton(self.frame)
        self.pushButton_updateUser.setGeometry(QtCore.QRect(30, 440, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_updateUser.setFont(font)
        self.pushButton_updateUser.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/gaming-console.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_updateUser.setIcon(icon2)
        self.pushButton_updateUser.setObjectName("pushButton_updateUser")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame)
        self.pushButton_logout.setGeometry(QtCore.QRect(30, 600, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logout.setFont(font)
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/check-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon3)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_deleteUser = QtWidgets.QPushButton(self.frame)
        self.pushButton_deleteUser.setEnabled(True)
        self.pushButton_deleteUser.setGeometry(QtCore.QRect(30, 530, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_deleteUser.setFont(font)
        self.pushButton_deleteUser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_deleteUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_deleteUser.setStyleSheet("QPushButton {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteUser.setIcon(icon4)
        self.pushButton_deleteUser.setAutoDefault(False)
        self.pushButton_deleteUser.setObjectName("pushButton_deleteUser")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 30, 781, 151))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;\n"
"    border-radius: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton_simpan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_simpan.setGeometry(QtCore.QRect(660, 630, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_simpan.setFont(font)
        self.pushButton_simpan.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;   \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690;  \n"
"}\n"
"")
        self.pushButton_simpan.setDefault(False)
        self.pushButton_simpan.setFlat(False)
        self.pushButton_simpan.setObjectName("pushButton_simpan")
        self.label_nama = QtWidgets.QLabel(self.centralwidget)
        self.label_nama.setGeometry(QtCore.QRect(520, 440, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(520, 380, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(520, 500, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(520, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.pushButton_cari = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cari.setGeometry(QtCore.QRect(910, 290, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_cari.setFont(font)
        self.pushButton_cari.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;   \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690;  \n"
"}\n"
"")
        self.pushButton_cari.setDefault(False)
        self.pushButton_cari.setFlat(False)
        self.pushButton_cari.setObjectName("pushButton_cari")
        self.label_isiUsername = QtWidgets.QLabel(self.centralwidget)
        self.label_isiUsername.setGeometry(QtCore.QRect(650, 370, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_isiUsername.setFont(font)
        self.label_isiUsername.setObjectName("label_isiUsername")
        self.label_isiNama = QtWidgets.QLabel(self.centralwidget)
        self.label_isiNama.setGeometry(QtCore.QRect(650, 430, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_isiNama.setFont(font)
        self.label_isiNama.setObjectName("label_isiNama")
        self.label_isiPassword = QtWidgets.QLabel(self.centralwidget)
        self.label_isiPassword.setGeometry(QtCore.QRect(650, 490, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_isiPassword.setFont(font)
        self.label_isiPassword.setObjectName("label_isiPassword")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(650, 290, 231, 51))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_role = QtWidgets.QLabel(self.centralwidget)
        self.label_role.setGeometry(QtCore.QRect(520, 560, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_role.setFont(font)
        self.label_role.setObjectName("label_role")
        self.label_isiRole = QtWidgets.QLabel(self.centralwidget)
        self.label_isiRole.setGeometry(QtCore.QRect(650, 550, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_isiRole.setFont(font)
        self.label_isiRole.setObjectName("label_isiRole")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_dashboardA.clicked.connect(self.dashboard_admin)
        self.pushButton_insertUser.clicked.connect(self.insert_user)
        self.pushButton_updateUser.clicked.connect(self.update_user)
        self.pushButton_logout.clicked.connect(self.logout)

        self.pushButton_cari.clicked.connect(self.search)
        self.pushButton_simpan.clicked.connect(self.submit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu Utama Admin"))
        self.pushButton_insertUser.setText(_translate("MainWindow", "Tambahkan user"))
        self.pushButton_dashboardA.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_updateUser.setText(_translate("MainWindow", "Perbarui Data User"))
        self.pushButton_logout.setText(_translate("MainWindow", " Logout"))
        self.pushButton_deleteUser.setText(_translate("MainWindow", "Hapus User"))
        self.label_2.setText(_translate("MainWindow", "Selamat Datang DI Kelola User"))
        self.pushButton_simpan.setText(_translate("MainWindow", "Hapus"))
        self.label_nama.setText(_translate("MainWindow", "Nama"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.pushButton_cari.setText(_translate("MainWindow", "Cari"))
        self.label_isiUsername.setText(_translate("MainWindow", "..."))
        self.label_isiNama.setText(_translate("MainWindow", "..."))
        self.label_isiPassword.setText(_translate("MainWindow", "..."))
        self.label_role.setText(_translate("MainWindow", "Role"))
        self.label_isiRole.setText(_translate("MainWindow", "..."))

    def dashboard_admin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def insert_user(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = iu.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def update_user(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = uu.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def logout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = login.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def search(self):
        id = self.lineEdit_id.text()
        if not id:
            return QtWidgets.QMessageBox.warning(None, "Error", "Tolong masukkan id!")
        
        user = user_controller.select_data_by_id(id)
        if user == None:
            return QtWidgets.QMessageBox.warning(None, "Error", "Data tidak ditemukan!")
        
        self.label_isiUsername.setText(user["username"])
        self.label_isiNama.setText(user["nama"])
        self.label_isiPassword.setText(user["password"])
        self.label_isiRole.setText(user["role"])

    def submit(self):
        id = self.lineEdit_id.text()
        if not id:
            return QtWidgets.QMessageBox.warning(None, "Error", "Tolong masukkan id!")
        
        user = user_controller.select_data_by_id(id)
        if user == None:
            return QtWidgets.QMessageBox.warning(None, "Error", "Data tidak ditemukan!")
        
        user_controller.delete_data(id)
        QtWidgets.QMessageBox.information(None, "Sukses", "Data user berhasil dihapus")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
