# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import dashboard_admin as da
import update_user as uu
import delete_user as du
import login
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 801)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 781))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;   /* biru muda lembut */\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game-console (1).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 160, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label.setObjectName("label")
        self.pushButtoninsertUser = QtWidgets.QPushButton(self.frame)
        self.pushButtoninsertUser.setEnabled(True)
        self.pushButtoninsertUser.setGeometry(QtCore.QRect(30, 350, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtoninsertUser.setFont(font)
        self.pushButtoninsertUser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButtoninsertUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtoninsertUser.setStyleSheet("QPushButton {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtoninsertUser.setIcon(icon)
        self.pushButtoninsertUser.setAutoDefault(False)
        self.pushButtoninsertUser.setObjectName("pushButtoninsertUser")
        self.pushButton_updateUser = QtWidgets.QPushButton(self.frame)
        self.pushButton_updateUser.setGeometry(QtCore.QRect(30, 440, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_updateUser.setFont(font)
        self.pushButton_updateUser.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game_14776131.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_updateUser.setIcon(icon1)
        self.pushButton_updateUser.setObjectName("pushButton_updateUser")
        self.pushButton_dashboardA = QtWidgets.QPushButton(self.frame)
        self.pushButton_dashboardA.setGeometry(QtCore.QRect(30, 260, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dashboardA.setFont(font)
        self.pushButton_dashboardA.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/xbox_906325.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dashboardA.setIcon(icon2)
        self.pushButton_dashboardA.setObjectName("pushButton_dashboardA")
        self.pushButton_deleteUser = QtWidgets.QPushButton(self.frame)
        self.pushButton_deleteUser.setGeometry(QtCore.QRect(30, 520, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_deleteUser.setFont(font)
        self.pushButton_deleteUser.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/gaming-console.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_deleteUser.setIcon(icon3)
        self.pushButton_deleteUser.setObjectName("pushButton_deleteUser")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame)
        self.pushButton_logout.setGeometry(QtCore.QRect(30, 600, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logout.setFont(font)
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/check-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon4)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 30, 781, 151))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;\n"
"    border-radius: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label_2.setObjectName("label_2")
        self.comboBox_pilihRole = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_pilihRole.setGeometry(QtCore.QRect(670, 490, 231, 51))
        self.comboBox_pilihRole.setObjectName("comboBox_pilihRole")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(670, 420, 231, 51))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(540, 350, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.pushButton_simpan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_simpan.setGeometry(QtCore.QRect(720, 570, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_simpan.setFont(font)
        self.pushButton_simpan.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;   \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6690;  \n"
"}\n"
"")
        self.pushButton_simpan.setDefault(False)
        self.pushButton_simpan.setFlat(False)
        self.pushButton_simpan.setObjectName("pushButton_simpan")
        self.lineEdit_nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nama.setGeometry(QtCore.QRect(670, 260, 231, 51))
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(540, 430, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_nama = QtWidgets.QLabel(self.centralwidget)
        self.label_nama.setGeometry(QtCore.QRect(540, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nama.setFont(font)
        self.label_nama.setObjectName("label_nama")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(670, 340, 231, 51))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_role = QtWidgets.QLabel(self.centralwidget)
        self.label_role.setGeometry(QtCore.QRect(540, 500, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_role.setFont(font)
        self.label_role.setObjectName("label_role")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_dashboardA.clicked.connect(self.dashboard_admin)
        self.pushButton_updateUser.clicked.connect(self.update_user)
        self.pushButton_deleteUser.clicked.connect(self.delete_user)
        self.pushButton_logout.clicked.connect(self.logout)
        # self.pushButton_simpan.clicked.connect(self.insert_data)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu Utama Admin"))
        self.pushButtoninsertUser.setText(_translate("MainWindow", "Tambahkan User"))
        self.pushButton_updateUser.setText(_translate("MainWindow", "Perbarui Data User"))
        self.pushButton_dashboardA.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_deleteUser.setText(_translate("MainWindow", "Hapus User"))
        self.pushButton_logout.setText(_translate("MainWindow", " Logout"))
        self.label_2.setText(_translate("MainWindow", "Selamat Datang DI Kelola User"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.pushButton_simpan.setText(_translate("MainWindow", "Save"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.label_nama.setText(_translate("MainWindow", "Nama"))
        self.label_role.setText(_translate("MainWindow", "Role"))

    def dashboard_admin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = da.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def update_user(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = uu.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def delete_user(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = du.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

    def logout(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = login.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from User import User

user_controller = User()

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 801)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 781))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;   /* biru muda lembut */\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game-console (1).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 160, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(30, 350, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 440, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/game_14776131.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 260, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/xbox_906325.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 520, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/gaming-console.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 600, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: #5a5a5a; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;  \n"
"    color: white; \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/ASUS/Downloads/check-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 30, 781, 151))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #d9ecff;\n"
"    border-radius: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #5a5a5a\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(540, 390, 61, 16))
        self.label_username.setObjectName("label_username")
        self.comboBox_pilihKategori = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_pilihKategori.setGeometry(QtCore.QRect(620, 490, 281, 31))
        self.comboBox_pilihKategori.setObjectName("comboBox_pilihKategori")
        self.label_nama = QtWidgets.QLabel(self.centralwidget)
        self.label_nama.setGeometry(QtCore.QRect(540, 340, 47, 13))
        self.label_nama.setObjectName("label_nama")
        self.lineEdit_isiUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_isiUsername.setGeometry(QtCore.QRect(620, 390, 281, 20))
        self.lineEdit_isiUsername.setObjectName("lineEdit_isiUsername")
        self.pushButton_simpan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_simpan.setGeometry(QtCore.QRect(610, 590, 291, 51))
        self.pushButton_simpan.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;   \n"
"    color: black; \n"
"    border-radius: 6px;            \n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    text-align: center;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"\n"
"")
        self.pushButton_simpan.setObjectName("pushButton_simpan")
        self.label_level = QtWidgets.QLabel(self.centralwidget)
        self.label_level.setGeometry(QtCore.QRect(540, 500, 47, 13))
        self.label_level.setObjectName("label_level")
        self.lineEdit_Nama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nama.setGeometry(QtCore.QRect(620, 340, 281, 20))
        self.lineEdit_Nama.setObjectName("lineEdit_Nama")
        self.lineEdit_isiPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_isiPassword.setGeometry(QtCore.QRect(620, 440, 281, 20))
        self.lineEdit_isiPassword.setObjectName("lineEdit_isiPassword")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(540, 440, 61, 16))
        self.label_password.setObjectName("label_password")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 210, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #d9ecff;\n"
"    color: grey; \n"
"    border-radius: 6px;         \n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: center;\n"
"    vertical-align: middle; \n"
"    padding-left: 5px; \n"
"}\n"
"")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.comboBox_pilihKategori.addItems(["kasir", "admin"])

        self.pushButton_simpan.clicked.connect(self.submit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu Utama Admin"))
        self.pushButton.setText(_translate("MainWindow", "Tambahkan user"))
        self.pushButton_3.setText(_translate("MainWindow", "Perbarui Data User"))
        self.pushButton_4.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_5.setText(_translate("MainWindow", "Hapus User"))
        self.pushButton_6.setText(_translate("MainWindow", " Logout"))
        self.label_2.setText(_translate("MainWindow", "Selamat Datang DI Kelola User"))
        self.label_username.setText(_translate("MainWindow", "username"))
        self.label_nama.setText(_translate("MainWindow", "Nama"))
        self.pushButton_simpan.setText(_translate("MainWindow", "Simpan"))
        self.label_level.setText(_translate("MainWindow", "Role"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Tambahkan Data User"))

    def submit(self):
        nama = self.lineEdit_Nama.text()
        username = self.lineEdit_isiUsername.text()
        password = self.lineEdit_isiPassword.text()
        role = self.comboBox_pilihKategori.currentText()

        if not nama or not username or not password:
            return QtWidgets.QMessageBox.warning(None, "Error", "Tolong isi semua form!")
        
        user_controller.insert_data(nama, username, password, role)
        QtWidgets.QMessageBox.information(None, "Sukses", "Data user berhasil disimpan")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
